<link href="/skins/template/css/error.css" type="text/css"  rel="stylesheet" />

<script type="text/javascript"><!--


$(document).ready(function(){	

	   $("#menuForm").validate({

		   rules: {
		
			
			name: {
				required: true,
				minlength: 4
				
			}

	
		  }
		   

	  });
	   
});
</script>

<h2 class="menusfieldh2">Create a new menu</h2> 



<div class="menusfield">

<p>To create a new menu complete this form and click submit...</p> 
<?php echo $this->form; ?> 
 
</div> 