<link href="/skins/template/css/admin.css" type="text/css"  rel="stylesheet" />


<h2 class="menusfieldh2">Current Menus</h2> 



<div class="menusfield"> 
<?php if($this->menus != null) { ?> 
<div class="menusfieldname">
<h2>Menu Name</h2>
</div>


<div class="menusfieldactions">
<h2>Actions</h2>
</div>


<?php echo $this->partialLoop('partials/_menu-row.phtml', $this->menus); ?>


<?php }else{?> 





<p>You do not have any menu yet.</p> 
<?php }?> 



<div class="menusfieldcreate">
<a href='/menu/create'>Create a new menu</a>
</div> 

</div>