<link href="/skins/template/css/orders.css" type="text/css" rel="stylesheet">

<?php if($this->orders->count()>0){?>
<table id="orders">
	<tr>
		<th>Order ID</th>
		<th>Date</th>
		<th>Status</th>
		<th>Billed</th>
		<th>Shipped</th>
		<th>Details</th>
	</tr >
	<?php 
	  foreach ($this->orders as $order){
	  ?>
	  <tr style="background-color: <?php  if($order->status=='new'){echo '#B5FFA4';}elseif ($order->status=='cancelled'){echo '#FFC0C0';} elseif ($order->status=='shipped'){echo '#D6D6D6';}?>">
	  	<td><a href='details/id/<?php echo $order->id?>' ><?php echo $order->id?></a></td>
	  	<td><?php echo date('Y-m-d',$order->insert_date)?></td>
	  	<td><?php  if($order->status=='new') {echo "in progress";} else {echo $order->status; } ?></td>
	  	<td><?php echo $order->bfName.' '.$order->blName?> </td>
	  	<td><?php echo $order->sfName.' '.$order->slName?> </td>
	  	<td><a href="/ordersadmin/delete/id/<?php echo $order->id?>">Delete</a></td>
	  </tr>
	  
	  <?php 
	  }
	
	?>
</table>
<?php }else{?>
There are no orders
<?php }?>