 
<?php if(is_array($this->results) && count($this->results) > 0) { ?> 
<div class="search"><span>Your search for <em><?php echo $this->keywords; ?></em> returned <?php echo  count($this->results); ?>
 results.</span></div>
<?php foreach ($this->results as $result) { ?> 
<h1><a href='/page/<?php echo $result->slug; ?>'><?php echo  $result->name; ?>
</a></h1> 
<p><?php echo $result->description; ?></p> 
<?php }} else {?> 
<p>Your search did not return any results</p> 
<?php }?> 
 
 