<link href="/skins/template/css/error.css" type="text/css"  rel="stylesheet" />

<script type="text/javascript"><!--


$(document).ready(function(){	

	   $("#menuitemForm").validate({

		   rules: {
		
			
			label: {
				required: true,
				minlength: 1,
				maxlength:250
				
			}

	
		  }
		   

	  });
	   
});
</script>

<h2>Add Menu Item</h2> 
<p>Current Menu: <?php echo $this->menu->name;?></p> 
<p>To add a menu item fill out the form below and click submit...</p> 
<?php echo $this->form; ?> 