<link href="/skins/template/css/error.css" type="text/css"  rel="stylesheet" />

<script type="text/javascript"><!--


$(document).ready(function(){	

	   $("#uForm").validate({

		   rules: {
		
			
			username: {
				required: true,
				minlength: 4,	
				maxlength: 50
				
			},

			password: {
				required: true,
				minlength: 4,
				maxlength:50
				
			},

			first_name: {
				required: true,
				minlength: 4,
				maxlength:50
				
			},

			last_name: {
				required: true,
				minlength: 4,
				maxlength:50
				
			},

			address: {
				required: true,
				minlength: 4,
				maxlength:100
				
			},

			state: {
				required: true,
				minlength: 4,
				maxlength:100
				
			},
			zip: {
				required: true,
				minlength: 4,
				maxlength:100
				
			},
			city: {
				required: true,
				minlength: 4,
				maxlength:100
				
			}
			
	
		  }
		   

	  });
	   
});
</script>

<div class="loginfield" align="center"> 
 <fieldset>
<legend><h2>Create a new user</h2> </legend>

<p>To create a  user complete this form and click submit...</p> 
<?php echo $this->form; ?> 

</fieldset>
</div>
