<link href="/skins/template/css/admin.css" type="text/css"  rel="stylesheet" />




<h2 class="userlistfieldh2">Current Users</h2> 



<div class="userlistfield"> 
<?php if($this->users != null) { ?>  



<div class="userlistfieldname">
<h2>User Name</h2>
</div>

<div class="userlistfieldfirstname">
<h2>First Name</h2>
</div>

<div class="userlistfieldlastname">
<h2>Last Name</h2>
</div>

<div class="userlistfieldrole">
<h2>Role</h2>
</div>

<div class="userlistfieldactions">
<h2>Actions</h2>
</div>


<?php echo $this->partialLoop('partials/_user-row.phtml', $this->users); ?>



<?php }else{?> 





<p>You do not have any users yet.</p> 


<?php }?> 



<div class="userlistfieldcreate">
<a href='/user/create'>Create a new user</a>
</div> 

</div>














