<!--<link href="/skins/template/css/product.css" type="text/css"  rel="stylesheet" />

<div style="float:left;width: 390px">
<h2 style="color:#365386">Newest Articles</h2>
<?php /*if($this->articles){

    foreach ($this->articles as $article){
    ?>
    <img src='<?php if($article->image){echo $article->image; } else {echo '/images/noimage.jpg';}?>' style='float:left;'/>
	<h4 style="float:left;"> <a href='/page/<?php echo $article->slug; ?>' >  <?php echo $article->name?> </a></h4>
	
	<br style="clear: both;"/>
	
	<div><?php echo $article->description?> </div>

<?php 
    } 
}
?>
</div>


<div style="float:left;width: 340px">

<h2 style="color:#365386">Newest Products</h2>

<table id="products" >

<?php 
$i=1;
if (count($this->product)){ 

	foreach($this->product as $products){ 
	
	?>
    <tr>
	<td>
		<img src=<?php if($products['thump']=='') {$image="noimage.jpg";}else $image=$products['thump']; echo $imagelink="http://".$_SERVER['SERVER_NAME']."/images/products/".$image; ?> style="float:left;"/>
        <div style="margin-left: 105px;">
			<span class="prod"><a href="/products/<?php echo $products['slug'] ?>" ><?php echo $products['name']?></a> </span>
		
			<br />
			<br />
		
			<span class="prod"> $<?php echo $products['price']?> </span>
        
			<br />
			<br />
		
			<form action="/cart/add" method="post">
				<input type="hidden" name="prodID" value="<?php echo $products['id'] ?> ">
				<input type="submit" name="submit" value="" class="add">
			</form>
		</div>
	
		<br style="clear: both"/>
	
	</td>
   </tr>
	   
<?php

	} 
}
 */?>
</table>
</div>
        -->
        
        <?php echo $this->form; ?>
        
