<link href="/skins/template/css/error.css" type="text/css"  rel="stylesheet" />

<script type="text/javascript"><!--


$(document).ready(function(){	

	   $("#uForm").validate({

		   rules: {
		
			
			username: {
				required: true,
				minlength: 4,
				maxlength: 50
				
			},

			first_name: {
				required: true,
				minlength: 4,
				maxlength:50
				
			},

			last_name: {
				required: true,
				minlength: 4,
				maxlength:50
				
			},

			address: {
				required: true,
				minlength: 4,
				maxlength:100
				
			},

			state: {
				required: true,
				minlength: 4,
				maxlength:100
				
			},
			zip: {
				required: true,
				minlength: 4,
				maxlength:100
				
			},
			city: {
				required: true,
				minlength: 4,
				maxlength:100
				
			}
			
	
		  }
		   

	  });
	   
});
</script>

<h2>Update user</h2> 
<?php if($this->error){
       echo "You can't modify other users information";
    }
    else{
        echo $this->form; 
    ?> 
<p> 
    <a href='/user/password/id/ 
               <?php echo $this->form->getElement('id')->getValue(); ?>'> 
        Update Password 
    </a> 
</p> 
<?php }?>