





	
	<div class="userlistfieldname"><?php echo $this->username ?></div>
<div class="userlistfieldfirstname"><?php echo $this->first_name ?></div>
<div class="userlistfieldlastname"><?php echo $this->last_name ?></div>
<div class="userlistfieldrole"><?php echo $this->role ?></div>
	
	
	
	
	
	 <div class="userlistfieldactions">
        <div class="userlistfieldactionsspan"><a href='/user/update/id/<?php echo $this->id;?>'>Update</a></div>
		
        <div class="userlistfieldactionsspan"><a href='/user/delete/id/<?php echo $this->id;?>'>Delete</a></div> 
       
    </div>
	