
    <div class="menusfieldactions">
        <div class="menusfieldactionsspan"><a href='/menu/edit/id/<?php echo $this->id;?>'>Edit</a></div>
		
        <div class="menusfieldactionsspan"><a href='/menu/move/direction/up/id/<?php echo $this->id;?>'>Move up</a></div> 
        <div class="menusfieldactionsspan"><a href='/menu/move/direction/down/id/<?php echo $this->id;?>'>Move down</a></div> 
        <div class="menusfieldactionsspan"><a href='/menuitem/index/menu/<?php echo $this->id;?>'>Manage Menu Items</a></div>
        <div class="menusfieldactionsspan"><a href='/menu/delete/id/<?php echo $this->id;?>'>Delete</a></div>
    </div>
	<div class="menusfieldname"><?php echo $this->name ?></div>
	
	


