<?php if ($this->pageCount){ 
    // you need to add each of the request parameters to url 
    $params = Zend_Controller_Front::getInstance()->getRequest()->getParams(); 
    // remove the system parameters 
    unset($params['module']); 
    unset($params['controller']); 
    unset($params['action']); 
?> 
<div class="paginationControl"> 

<!-- Previous page link --> 
<?php if (isset($this->previous)){ ?> 
  <a href="<?php echo $this->url(array_merge( 
      $params, array('page' => $this->previous))); ?>" style="color: #0C76CF;"> 
    &lt; Previous 
  </a> | 
<?php } else { ?> 
  <span class="disabled" style="color: black;">&lt; Previous</span> | 
<?php } ?> 
 
<!-- Numbered page links --> 
<?php foreach ($this->pagesInRange as $page){ ?> 
  <?php if ($page != $this->current){ ?> 
    <a href="<?php echo $this->url(array_merge($params, 
        array('page' => $page))); ?>" style="color: #9B9B9B"> 
        <?php echo $page; ?> 
    </a> | 
  <?php } else { ?> 
    <?php echo $page; ?> | 
  <?php }}?> 
 
<!-- Next page link --> 
<?php if (isset($this->next)){ ?> 
  <a href="<?php echo $this->url( 
      array_merge($params, array('page' => $this->next))); ?>" style="color: #0C76CF;"> 
    Next &gt; 
  </a> 
<?php } else { ?> 
  <span class="disabled" style="color: black;"> Next &gt;</span> 
<?php } ?> 
</div> 
<?php } ?> 