       <script>
    $(document).ready(function(){
      
        $(".item").click(function(){
           
        var currentId = $('a').attr('class');
        alert(currentId);
            
      //  $.get("/cart/add/", { prodID: $(this).val()}, function(){
               
            // reloadPage();
         //  });
     
                   
        }); 
             
    });
</script>
<link href="skins/blues/css/product.css" type="text/css"  rel="stylesheet" />
<div class="product_header">
    <h1 class="pheading" style="color:#365386">Products</h1>


<br />

<div class="ppagination"><?php echo $this->paginationControl($this->paginator,
     'Sliding',
     'partials/pagination-control.phtml'); ?> </div>
<br />
</div>
    <div class="items">
<?php
$i=1;
if (count($this->paginator)){

	foreach($this->paginator as $products){
	if($i%2!=0) echo "<tr>";
	?>

	<div class="item">
   
			<h3><a href="<?php echo $this->baseUrl(); ?>/products/<?php echo $products['slug'] ?>" ><?php echo $products['name']?></a></h3>
				<div class="picture">
                    <img src=<?php if($products['thump']=='') {$image="noimage.jpg";}else $image=$products['thump']; echo $imagelink="http://".$_SERVER['SERVER_NAME']."/images/products/".$image; ?> />
           </div>
    			<p>
    				<?php  echo $this->product->content; ?>
    					<span>$<?php echo $products['price']?> </span>
    					<a id="hello" href="/cart/details/">Details</a>
                            <a class="<?php echo $products['id']; ?>" href="#" >Add to cart</a>
                                          
				</p>
    			</div>

                <?php
    if($i%2==0) echo "</tr>";
	$i++;
	}
}
?>
			</div>
       <ul class="categories">
             <h3>Browse by categories</h3>
             <br />
             <?php foreach($this->cateView as $catV): ?>
            	<li><a href="/products/catsearch/id/<?php echo $catV->id; ?>"><?php echo $catV->name; ?></a></li>
             <?php endforeach; ?>

        </ul>

