<link href="/skins/template/css/admin.css" type="text/css"  rel="stylesheet" />


<h2 class="pageadminfieldh2">Products</h2> 

<div class="pageadminfield"> 
<?php if($this->products != null) { ?> 


<div class="pageadminfieldname">
<h2>Product Name</h2>
</div>


<div class="pageadminfieldactions">
<h2>Actions</h2>
</div>

     <?php echo $this->partialLoop('partials/_products-row.phtml', $this->products); ?>

<?php }else{?> 

<p>You do not have any products yet.</p> 
<?php }?> 
<div class="pageadminfieldcreate">
<a href='/productsedit/create'>Create a new page</a>
</div>

</div>