<link href="/skins/template/css/admin.css" type="text/css"  rel="stylesheet" />

<h2 class="pageadminfieldh2">Current Pages</h2> 

<div class="pageadminfield"> 
<?php if($this->pages != null) { ?> 

<div class="pageadminfieldname">
<h2>Page Name</h2>
</div>


<div class="pageadminfieldactions">
<h2>Actions</h2>
</div>

    <?php echo $this->partialLoop('partials/_page-row.phtml', $this->pages); ?> 

<?php }else{?> 


<p>You do not have any pages yet.</p> 
<?php }?> 
<div class="pageadminfieldcreate">
<a href='/pageadmin/create'>Create a new page</a>
</div>

</div>