<script>
    $(document).ready(function(){
       $('#submit').click(function(){
           alert("hello world");
       });
    });
</script>
<link href="skins/blues/css/product.css" type="text/css"  rel="stylesheet" />






<div class="product_details">

<?php foreach($this->finalProduct as $addedToCart): ?>

<h3><?php   echo $addedToCart['name']. "<br />";  ?></h3>

<div class="product_details_left">
<img src=<?php if($addedToCart['thump']=='') {
     $image="noimage.jpg";
     
     }
     else $image=$addedToCart['thump'];
     echo $imagelink="http://".$_SERVER['SERVER_NAME']."/images/products/".$image; ?> />
</div>


<div class="product_details_right">


<p>
<?php   echo $addedToCart['meta_description']. "<br />"; ?>

</p>

<span>Price : $<?php   echo $addedToCart['price']. "<br />"; ?></span>
<br />

<?php endforeach; ?>

  <div id="finalDiv">
      
  </div>
<div class="product_details_right_updateq">
<form action="/products/updatecart/price/<?php echo trim($addedToCart['price']); ?>" method="post">
        <!--  <form action="#"> -->
        <label>Update Quantity</label>
        <input type="text" name="updateCart" value="<?php echo count($addedToCart['name']); ?>"/>
		<br />
        <input type="submit" name="update Cart" value="Update Cart" />
    </form>
	</div>
<br />
<a href="/products/<?php echo $products['slug'] ?>" >Go Back to Products Page</a>

</div>

</div>