
<link href="/skins/template/css/product.css" type="text/css"  rel="stylesheet" />


<div id="product-wrapper">
<?php if($this->cat){?>


<h1 style="color:#365386"><?php echo $this->cat->name ?></h1>
<br />


<br />

<div style="width:700px;">
<?php  echo $this->product->content;?>
</div>



<?php }else{?>

	<h1><?php echo $this->no;?></h1>
<?php }?>
</div>







<div class="product_details">

<h3><?php  echo $this->product->name; ?></h3>

<div class="product_details_left">
<img src=<?php if($this->product['thump']=='') {$image="noimage.jpg";}else $image=$this->product['thump']; echo $imagelink="http://".$_SERVER['SERVER_NAME']."/images/products/".$image; ?> />
</div>


<div class="product_details_right">


<p>
<?php  echo $this->product->content; ?>

</p>

<span>Price : $<?php  echo $this->product->price; ?></span>
<br />


<a id="cartclick" href="/products/addtocart/id/<?php echo $products['id']; ?>">Add to cart</a>
<br />
<a href="/products/<?php echo $products['slug'] ?>" >Go Back to Products Page</a>

</div>

</div>

